name: Auto-update AutoMixConf

on:
  schedule:
    - cron: cron: '*/15 * * * *'  # Каждые 15 минут
  workflow_dispatch:  # Ручной запуск

jobs:
  update-automixconf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install PyGithub
      
      - name: Update AutoMixConf
        run: python auto_mix_configs.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: tourrty-droid
          GITHUB_REPO: GoidaVpn
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "auto: update AutoMixConf" && git push
