name: Auto Update Configs

on:
  schedule:
    - cron: '*/30 * * * *' # Запуск каждые 30 минут
  push:
    branches:
      - main # Запуск при сохранении файлов
  workflow_dispatch: # Запуск по кнопке

jobs:
  update-configs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Клонирование вашего репозитория
      uses: actions/checkout@v4

    - name: Настройка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Установка библиотек
      run: pip install requests

    - name: Выполнение скрипта
      run: python merge_configs.py

    - name: Сохранение изменений
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Добавляем папки data и logs в Git
        if [ -d "data" ]; then git add data/; fi
        if [ -d "logs" ]; then git add logs/; fi
        
        if ! git diff --staged --quiet; then
          git commit -m "🚀 Автоматическое обновление 30 минут"
          git push
        else
          echo "Изменений нет."
        fi
