name: Auto Update Configs

on:
  schedule:
    - cron: '0 */3 * * *' # Запуск каждые 3 часа
  workflow_dispatch: # Кнопка ручного запуска

jobs:
  update-configs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Клонирование вашего репозитория
      uses: actions/checkout@v4

    - name: Настройка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Установка библиотек
      run: pip install requests

    - name: Выполнение скрипта
      run: python merge_configs.py

    - name: Сохранение изменений
      run: |
        git config --local user.email "41898282+github-actions[bot]@://github.com"
        git config --local user.name "github-actions[bot]"
        touch AutoConfigs.txt 
        git add AutoConfigs.txt
        # Добавляем отслеживание всей папки с логами
        if [ -d "logs" ]; then git add logs/; fi
        if ! git diff --staged --quiet; then
          git commit -m "Обновление ТОП-7 конфигов и ротация логов [skip ci]"
          git push
        else
          echo "Изменений в файлах нет."
        fi
