name: Ежечасное обновление VLESS-конфигов

on:
  schedule:
    # Запуск в 00 минут каждого часа
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update_configs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Установка зависимостей
        run: |
          pip install requests

      - name: Запуск скрипта обновления
        run: python update_configs.py

      - name: Отправка изменений в репозиторий
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/Githubmirror/vless/vless.txt
          git diff --cached --quiet || git commit -m "Автоматическое обновление конфигураций VLESS за $(date +'%Y-%m-%d %H:%M:%S')"
          git push
